=== Al4r1c/RestServer/public/i18n/xmli18n.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT language (errorMessage|trad)*>
<!ATTLIST language lang CDATA #REQUIRED>

	<!ELEMENT errorMessage (message+)>
	<!ELEMENT trad (message+)>

		<!ELEMENT message (#PCDATA)>
		<!ATTLIST message code CDATA #REQUIRED>

=== Al4r1c/RestServer/public/i18n/en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "xmli18n.dtd">

<language lang="en">

    <trad>
        <message code="notice">Notice</message>
        <message code="warning">Warning</message>
        <message code="error">Error</message>
        <message code="fatalerror">Fatal error</message>
        <message code="file">File</message>
        <message code="line">Line</message>
	    <message code="appliError">Application</message>
	    <message code="fileSysError">File system</message>
	    <message code="fileError">File</message>
        <message code="restReqError">Request</message>
        <message code="restResError">Response</message>
        <message code="serverError">Server and execution environment information</message>
        <message code="headManError">Header Manager</message>
        <message code="confError">Configuration file</message>
        <message code="dataError">Data error</message>
    </trad>

    <errorMessage>
	    <message code="10000">Error displaying class "%s" does not exist.</message>
	    <message code="10100">OS "%s" is not suported or is not valid.</message>
	    <message code="10101">Base path "%s" is not absolute.</message>
	    <message code="10102">Base path "%s" does not exist.</message>
	    <message code="10103">File "%s" does not exist, unable to get file perms.</message>
	    <message code="10104">File "%s" could not be created (permissions problem ?).</message>
	    <message code="10105">File "%s" does not exist and nothing got charged.</message>
	    <message code="10106">File with extension "%s" can't be loaded. (File: %s)</message>
	    <message code="10200">Empty filename.</message>
	    <message code="10201">The file %s has no extension.</message>
	    <message code="10202">Empty directory name.</message>
	    <message code="10203">File "%s" does not exist.</message>
	    <message code="10204">Destination folder "%s" does not exist.</message>
	    <message code="10205">Error while trying to create file "%s".</message>
	    <message code="20000">Invalid HTML method "%s". Check http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html for more informations about valid methods.</message>
	    <message code="20001">No valid return format found.</message>
	    <message code="20002">Invalid server data.</message>
	    <message code="20100">Invalid response data.</message>
	    <message code="20101">HTTP code "%s" is not valid. Check http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html for more informations about HTTP code.</message>
	    <message code="20102">Output format set (%s) does not exist in available outputs.</message>
	    <message code="20103">Default output format invalid.</message>
	    <message code="20104">Accepted output format are invalid.</message>
	    <message code="20105">Invalid charset %s.</message>
	    <message code="20106">Default output format "%s" not found in configuration.</message>
	    <message code="20107">Specified output rendering class (%s) not found.</message>
	    <message code="20200">Key %s does not exist in the URI.</message>
	    <message code="20201">Requested parameter %s does not exist.</message>
	    <message code="20300">Missing server variables.</message>
	    <message code="20301">Invalid HTML method "%s". Check http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html for more informations about valid methods.</message>
	    <message code="20400">Response header "%s" is invalid. Check http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html for more informations about headers.</message>
		<message code="30000">Framework's configuration file not found. (Should be located: %s)</message>
	    <message code="30001">Key %s must be present but does not exist in the configuration.</message>
	    <message code="30002">Key %s does not exist in the configuration.</message>
	    <message code="40000">Language "%s" is not associated with any translation. Language used instead: %s.</message>
	    <message code="40001">Default language "%s" file (%s) not found. Language loaded instead: %s.</message>
	    <message code="40002">Default language "%s" file (%s) invalid (%s). Language loaded instead: %s.</message>
	    <message code="40003">Language file for %s not found. (Should be: %s)</message>
	    <message code="40004">Language file for %s invalid (%s). (%s)</message>
	    <message code="40005">No valid translation file set or found.</message>
        <message code="40006">Translation for the entity "%s.%s" not found.</message>
    </errorMessage>

</language>

=== Al4r1c/RestServer/public/i18n/fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "xmli18n.dtd">

<language lang="fr">

    <trad>
        <message code="notice">Remarque</message>
        <message code="warning">Attention</message>
        <message code="error">Erreur</message>
        <message code="fatalerror">Erreur critique</message>
        <message code="file">Fichier</message>
        <message code="line">Ligne</message>
    </trad>

	<errorType>
		<message code="10">Paramètre invalide</message>
		<message code="101">Système de fichier</message>
		<message code="102">Fichier</message>
		<message code="200">Requête</message>
		<message code="201">Réponse</message>
		<message code="202">Gestionnaire Rest</message>
		<message code="203">Variables de serveur et d'exécution</message>
		<message code="204">Gestionnaire des entêtes</message>
		<message code="300">Fichier de configuration</message>
		<message code="">Erreur de donnée</message>
	</errorType>

    <errorMessage>
	    <message code="1000">Paramètre de la fonction %s::%s() doit être du type %s, %s obtenu.</message>
	    <message code="10100">L'OS "%s" n'est pas supporté ou est invalide.</message>
	    <message code="10101">Le chemin de base "%s" n'est pas absolu.</message>
	    <message code="10102">Le chemin de base "%s" n'existe pas.</message>
	    <message code="10103">Le fichier "%s" n'existe pas, impossible d'en récupérer les droits.</message>
	    <message code="10104">Le fichier "%s" n'a pas pu être créé (problème de permission ?).</message>
	    <message code="10105">Le fichier "%s" n'existe pas et rien n'a été chargé.</message>
	    <message code="10106">Les fichiers avec l'extension "%s" ne peuvent être chargés. (Fichier: %s)</message>
	    <message code="10200">Le nom du fichier est vide.</message>
	    <message code="10201">Le fichier %s est dépourvue d'extension.</message>
	    <message code="10202">Le nom du répertoire est vide.</message>
	    <message code="10203">Le fichier "%s" n'existe pas.</message>
	    <message code="10204">Le dossier de destination "%s" n'existe pas.</message>
	    <message code="10205">Erreur lors de la tentative de créer le fichier "%s".</message>
	    <message code="20000">Méthode HTML "%s" invalide. Consulter http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html pour plus d'informations à propos des méthodes.</message>
	    <message code="20001">Aucun format de retour valide trouvé.</message>
	    <message code="20002">Données serveur invalides.</message>
	    <message code="20100">Données de la réponse invalides.</message>
	    <message code="20101">Code HTTP "%" invalide. Consulter http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html à propos des code HTTP.</message>
	    <message code="20102">Le format de retour configuré (%s) n'existe pas dans les rendus disponibles.</message>
	    <message code="20103">Le format de retour par défaut est invalide.</message>
	    <message code="20104">Les formats de retour acceptés sont invalides.</message>
	    <message code="20105">Charset %s invalide.</message>
	    <message code="20106">Le format de sortie par défaut "%s" n'a pas été trouvé dans la configuration.</message>
	    <message code="20107">La classe du rendu de la sortie spécifiée (%s) n'a pas été trouvée.</message>
	    <message code="20200">La clef %s n'existe pas dans l'URI.</message>
	    <message code="20201">Le paramètre demandé %s n'existe pas.</message>
	    <message code="20300">Des variables serveurs manquent.</message>
	    <message code="20301">Méthode HTML "%s" invalide. Consulter http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html pour plus d'informations à propos des méthodes.</message>
	    <message code="20400">L'entête HTTP "%s" pour la réponse est invalide. Consulter http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html pour plus d'information sur les entêtes.</message>
	    <message code="30000">Le fichier de configuration du framework est introuvable. (Devrait être: %s)</message>
	    <message code="30001">La clef %s est obligatoire dans la configuration mais n'existe pas.</message>
	    <message code="30002">La clef %s n'existe pas dans la configuration.</message>
    </errorMessage>

</language>
